### ISSUE TITLE
hosts backend is not parsing final line

### ISSUE THREAD

**Issue by pemensik** [crossdistro/netresolve#3]
New Fedora releases started failing tests. Found that is because default hosts file shipped does not contain final new line. IPv6 address of localhost is not terminated by newline. Backend does not parse it and it fails netresolve test. [Fedora bug](https://bugzilla.redhat.com/show_bug.cgi?id=1736166)

Reproduce the issue:
```
echo "127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4" > hosts
echo -n "::1         localhost localhost.localdomain localhost6 localhost6.localdomain6" > hosts

NETRESOLVE_SYSCONFDIR=. tests/test-netresolve.sh
```

Fails at the end with:
```
...
++ ./netresolve --node localhost --service ''
+ diff -u /dev/fd/63 ./tests/data/localhost
++ ./netresolve --backends hosts --node localhost
--- /dev/fd/63	2019-09-10 10:15:40.122352456 -0400
+++ ./tests/data/localhost	2016-03-15 18:35:28.000000000 -0400
@@ -1,5 +1,6 @@
 response netresolve 0.0.1
 name localhost
+ip ::1 any any 0 0 0 0
 ip 127.0.0.1 any any 0 0 0 0
 secure
```

**Comment by pavlix** [comment]
Just merged the issue. Sorry for the gap, now I'm once again on GitHub much more often!
